//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DestoPesto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DestoPesto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://destopesto.gr/info/Accuracy_disclaimer_en.
        /// </summary>
        public static string Accuracy_disclaimerLink {
            get {
                return ResourceManager.GetString("Accuracy_disclaimerLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string AlertText {
            get {
                return ResourceManager.GetString("AlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Apple.
        /// </summary>
        public static string AppleLogin {
            get {
                return ResourceManager.GetString("AppleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δες το, Πες το.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When prompted make sure to tap &apos;Allow&apos; so that the app can use camera.
        /// </summary>
        public static string CameraDetails {
            get {
                return ResourceManager.GetString("CameraDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraTitle {
            get {
                return ResourceManager.GetString("CameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string CancleText {
            get {
                return ResourceManager.GetString("CancleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagory.
        /// </summary>
        public static string CatagoryText {
            get {
                return ResourceManager.GetString("CatagoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueText {
            get {
                return ResourceManager.GetString("ContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies Policy (in Greek).
        /// </summary>
        public static string CookiesPolicy {
            get {
                return ResourceManager.GetString("CookiesPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://destopesto.gr/info/cookies_policy_en.
        /// </summary>
        public static string CookiesPolicyLInk {
            get {
                return ResourceManager.GetString("CookiesPolicyLInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still Not Connected ?.
        /// </summary>
        public static string CreateAccountText {
            get {
                return ResourceManager.GetString("CreateAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage status updated Fail.
        /// </summary>
        public static string DamageSatusFail {
            get {
                return ResourceManager.GetString("DamageSatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage status updated successfully.
        /// </summary>
        public static string DamageSatusSuccess {
            get {
                return ResourceManager.GetString("DamageSatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DobText {
            get {
                return ResourceManager.GetString("DobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip this message next time.
        /// </summary>
        public static string DontShowAgain {
            get {
                return ResourceManager.GetString("DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With email / password.
        /// </summary>
        public static string EmailLogin {
            get {
                return ResourceManager.GetString("EmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Set Location Permission: &quot; Allow all the time &quot; in Settings.
        /// </summary>
        public static string EnableBGToast {
            get {
                return ResourceManager.GetString("EnableBGToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhere already exists an account with the email address asserted by Google.
        /// </summary>
        public static string ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL {
            get {
                return ResourceManager.GetString("ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration.
        /// </summary>
        public static string ERROR_CUSTOM_TOKEN_MISMATCH {
            get {
                return ResourceManager.GetString("ERROR_CUSTOM_TOKEN_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s account is disabled.
        /// </summary>
        public static string ERROR_DISABLED {
            get {
                return ResourceManager.GetString("ERROR_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already in use by a different account.
        /// </summary>
        public static string ERROR_EMAIL_ALREADY_IN_USE {
            get {
                return ResourceManager.GetString("ERROR_EMAIL_ALREADY_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid.
        /// </summary>
        public static string ERROR_INVALID {
            get {
                return ResourceManager.GetString("ERROR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhe password reset code is invalid. This can happen if the code is malformed or has already been used.
        /// </summary>
        public static string ERROR_INVALID_ACTION_CODE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_ACTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [email] address is malformed.
        /// </summary>
        public static string ERROR_INVALID_CREDENTIAL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_CREDENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The custom token format is incorrect.
        /// </summary>
        public static string ERROR_INVALID_CUSTOM_TOKEN {
            get {
                return ResourceManager.GetString("ERROR_INVALID_CUSTOM_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is malformed.
        /// </summary>
        public static string ERROR_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is invalid.
        /// </summary>
        public static string ERROR_INVALID_VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and email sign-in link accounts are not enabled.
        /// </summary>
        public static string ERROR_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous accounts are not enabled.
        /// </summary>
        public static string ERROR_OPERATION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_OPERATION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was too many attempts to sign in as this user.
        /// </summary>
        public static string ERROR_TOO_MANY_REQUESTS {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_REQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been disabled.
        /// </summary>
        public static string ERROR_USER_DISABLED {
            get {
                return ResourceManager.GetString("ERROR_USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user corresponding to the given [email] address, or the user has been deleted.
        /// </summary>
        public static string ERROR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not strong enough.
        /// </summary>
        public static string ERROR_WEAK_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WEAK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrongp.
        /// </summary>
        public static string ERROR_WRONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERROR_WRONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitText {
            get {
                return ResourceManager.GetString("ExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhe password reset code has expired.
        /// </summary>
        public static string EXPIRED_ACTION_CODE {
            get {
                return ResourceManager.GetString("EXPIRED_ACTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Facebook.
        /// </summary>
        public static string FacebookLogin {
            get {
                return ResourceManager.GetString("FacebookLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This has been fixed.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgetPasswordText {
            get {
                return ResourceManager.GetString("ForgetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exact password recovery instructions will be sent to your email. Follow them and in no time you will be back in the app.
        /// </summary>
        public static string ForgotPasswordPage {
            get {
                return ResourceManager.GetString("ForgotPasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPasswordPageText1 {
            get {
                return ResourceManager.GetString("ForgotPasswordPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email .
        /// </summary>
        public static string ForgotPasswordPageText2 {
            get {
                return ResourceManager.GetString("ForgotPasswordPageText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GenderText {
            get {
                return ResourceManager.GetString("GenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Catagories.
        /// </summary>
        public static string GetCatagoryText {
            get {
                return ResourceManager.GetString("GetCatagoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Google.
        /// </summary>
        public static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string GoToSetttingsText {
            get {
                return ResourceManager.GetString("GoToSetttingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Have An Account ?.
        /// </summary>
        public static string HaveAccountText {
            get {
                return ResourceManager.GetString("HaveAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeItemText {
            get {
                return ResourceManager.GetString("HomeItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works (in Greek).
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://destopesto.gr/info/how_it_works_en.
        /// </summary>
        public static string HowItWorksLink {
            get {
                return ResourceManager.GetString("HowItWorksLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s easy. Choose the category by pressing the appropriate button below, take a photo and send it.
        /// </summary>
        public static string InstructionsMessage {
            get {
                return ResourceManager.GetString("InstructionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhe password reset code is invalid. This can happen if the code is malformed or has already been used.
        /// </summary>
        public static string INVALID_ACTION_CODE {
            get {
                return ResourceManager.GetString("INVALID_ACTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidEntryStyle.
        /// </summary>
        public static string InvalidEntryStyle {
            get {
                return ResourceManager.GetString("InvalidEntryStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s nice to see you here .
        /// </summary>
        public static string LetsRegisterLineOneText {
            get {
                return ResourceManager.GetString("LetsRegisterLineOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s create an account.
        /// </summary>
        public static string LetsRegisterLineTwoText {
            get {
                return ResourceManager.GetString("LetsRegisterLineTwoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage is Reported Nearby Please Check.
        /// </summary>
        public static string LocalNotificationDec {
            get {
                return ResourceManager.GetString("LocalNotificationDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Report Alert.
        /// </summary>
        public static string LocalNotificationTitle {
            get {
                return ResourceManager.GetString("LocalNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When prompted make sure to tap &apos;Allow While Using App&apos; so that your app can work flawlessly.
        /// </summary>
        public static string LocationPermission {
            get {
                return ResourceManager.GetString("LocationPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app uses location data when a photo is taken as part of the control on the accuracy of information provided. This data is stored in the application to allow it to determine the exact location that the photo was taken. .
        /// </summary>
        public static string LocationPrompt {
            get {
                return ResourceManager.GetString("LocationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Access.
        /// </summary>
        public static string LocationTitle {
            get {
                return ResourceManager.GetString("LocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutItemText {
            get {
                return ResourceManager.GetString("LogoutItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δες το, Πες το.
        /// </summary>
        public static string MapHeaderText {
            get {
                return ResourceManager.GetString("MapHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is not responding because internet connection is lost or the server is down. Close the app and try again in a minute.
        /// </summary>
        public static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommened to keep the app running as there are still pending photos to be uploaded.
        /// </summary>
        public static string NotificationContentText {
            get {
                return ResourceManager.GetString("NotificationContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When prompted make sure to tap &apos;Allow&apos; so that the app can notify you at important updates, such as successful uploads.
        /// </summary>
        public static string NotificationDetails {
            get {
                return ResourceManager.GetString("NotificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users have reported this.
        /// </summary>
        public static string NumUserText {
            get {
                return ResourceManager.GetString("NumUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Oktext {
            get {
                return ResourceManager.GetString("Oktext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If notifications are not allowed the app will not run .
        /// </summary>
        public static string PermissionsNotGrandedText {
            get {
                return ResourceManager.GetString("PermissionsNotGrandedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notifications, Camera and Location Access.
        /// </summary>
        public static string PermissionsTitle {
            get {
                return ResourceManager.GetString("PermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app needs your permission to access all three in order to be fully functional.
        /// </summary>
        public static string PermissionTitleDetails {
            get {
                return ResourceManager.GetString("PermissionTitleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy (in Greek).
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://destopesto.gr/info/PrivacyPolicy_en.
        /// </summary>
        public static string PrivacyPolicyLInk {
            get {
                return ResourceManager.GetString("PrivacyPolicyLInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        public static string RePasswordPlaceHolder {
            get {
                return ResourceManager.GetString("RePasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to Report a Damage.
        /// </summary>
        public static string ReportDamageClick {
            get {
                return ResourceManager.GetString("ReportDamageClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reported Failed.
        /// </summary>
        public static string ReportFailed {
            get {
                return ResourceManager.GetString("ReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report this damage as fixed.
        /// </summary>
        public static string ReportFix {
            get {
                return ResourceManager.GetString("ReportFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Reported Successfully.
        /// </summary>
        public static string ReportSuccess {
            get {
                return ResourceManager.GetString("ReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photos only over Wifi.
        /// </summary>
        public static string sendDataWifi {
            get {
                return ResourceManager.GetString("sendDataWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR Sign Up With.
        /// </summary>
        public static string seprationSignupText {
            get {
                return ResourceManager.GetString("seprationSignupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        public static string seprationSimpleText {
            get {
                return ResourceManager.GetString("seprationSimpleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingItemText {
            get {
                return ResourceManager.GetString("SettingItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        public static string SigninText {
            get {
                return ResourceManager.GetString("SigninText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Failed .
        /// </summary>
        public static string SignupFail {
            get {
                return ResourceManager.GetString("SignupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup Sucessfull.
        /// </summary>
        public static string SignupSuccess {
            get {
                return ResourceManager.GetString("SignupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty email is forbitten.
        /// </summary>
        public static string SomethingIsNotRightEmail {
            get {
                return ResourceManager.GetString("SomethingIsNotRightEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be null.
        /// </summary>
        public static string SomethingIsNotRightPassword {
            get {
                return ResourceManager.GetString("SomethingIsNotRightPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit app now.
        /// </summary>
        public static string StopServiceCommandTitle {
            get {
                return ResourceManager.GetString("StopServiceCommandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My submisions.
        /// </summary>
        public static string SubmisionsText {
            get {
                return ResourceManager.GetString("SubmisionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions (in Greek).
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions have been disabled and the app will not run. You need to enable permissions manually in order to continue.
        /// </summary>
        public static string TokenExpiredText {
            get {
                return ResourceManager.GetString("TokenExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I disagree.
        /// </summary>
        public static string TurnOff {
            get {
                return ResourceManager.GetString("TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhe user corresponding to the given password reset code has been disabled.
        /// </summary>
        public static string USER_DISABLED {
            get {
                return ResourceManager.GetString("USER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhere is no user corresponding to the password reset cod.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserNameText {
            get {
                return ResourceManager.GetString("UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision (in Greek).
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://destopesto.gr/info/vision_en.
        /// </summary>
        public static string VisionLink {
            get {
                return ResourceManager.GetString("VisionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τhe new password is not strong enough.
        /// </summary>
        public static string WEAK_PASSWORD {
            get {
                return ResourceManager.GetString("WEAK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the app.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome .
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how to continue.
        /// </summary>
        public static string WelcomeText_2 {
            get {
                return ResourceManager.GetString("WelcomeText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
